# Generated by Django 6.1 on 2026-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('relation', models.CharField(choices=[('FRIEND', 'دوست')], max_length=10)),
                ('birthday_date', models.DateField()),
            ],
            options={
                'ordering': ['-birthday_date'],
            },
        ),
    ]
